In [3]:
import pandas as pd
import numpy as np

In [2]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [8]:
Inc = pd.DataFrame([Husband_Income, Wife_Income, Mother_In_Law_Income]).values
Inc

array([[100, 220, 140],
       [150, 200, 130],
       [ 90,  80, 100]], dtype=int64)

In [6]:
Cons = pd.DataFrame([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption]).values
Cons

array([[ 50,  50,  60],
       [100,  80, 140],
       [100,  20, 140]], dtype=int64)

In [10]:
Inc_Tax = Inc*(1-0.13)
Inc_Tax

array([[ 87. , 191.4, 121.8],
       [130.5, 174. , 113.1],
       [ 78.3,  69.6,  87. ]])

In [11]:
P = Inc_Tax-Cons
P

array([[ 37. , 141.4,  61.8],
       [ 30.5,  94. , -26.9],
       [-21.7,  49.6, -53. ]])

In [5]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [6]:
A@x

array([26, 30])

In [7]:
A=np.array( [ [1,9,8,5] , [3,6,3,2] , [3,3,3,3], [0,2,5,9], [4,4,1,2] ] )
B=np.array( [ [1,-1,0,1,1] , [-2,0,2,-1,1] ] )

In [8]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [9]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [14]:
A = np.array([x,y,z]).T
A

array([[ 1,  2, -1],
       [ 2,  1,  1],
       [ 1, -1, -1],
       [ 0,  1,  0],
       [ 4,  0,  0]])

In [15]:
A.T@A

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [16]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [18]:
C = Count_DF.values

P = Price_DF.values

Boris_inc = C[1]*P[1]
Boris_inc

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [19]:
com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [21]:
s = C*P@com
s

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [23]:
d = C*P@(np.ones(5)-com)
d

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])