In [10]:
import numpy as np
import pandas as pd

In [5]:
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])
share_living_space = apartment[1]/apartment[0]
apartment = np.delete(apartment, [0, 1])
apartment = np.append(apartment, share_living_space)
apartment.shape

(5,)

In [8]:
a = np.array([120, 150, 90])
b = np.array([130, 130, 130])
c = np.array([2, 3, 2.5])
c = c * 72
s = a + b + c
s

array([394., 496., 400.])

In [11]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [13]:
a = Hut_Paradise_DF.values

In [15]:
a[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [16]:
a[:, 3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [17]:
a[:, 3][2]

10

In [18]:
len(a)

9

In [20]:
a[:, 1] - a[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [23]:
a[:, 0]*0.4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [24]:
time=np.array([10,20,30,15,5,40,20,8,20])
a[:, 4] @ time

1348

In [25]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [27]:
c=2*v-3*w
c

array([-3, 14,  3,  4,  2])

In [28]:
c @ u

0

In [29]:
u/np.linalg.norm(u)

array([0.8660254 , 0.        , 0.28867513, 0.28867513, 0.28867513])